experiment_name: phi_gru_10_classes

model:
  _target_: models.Phi_GRU
  num_classes: 35
  n_mel_bins: 64
  hidden_dim: 32

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
  weight_decay: 1e-5

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.5
  patience: 5
  verbose: true

dataset:
  defaults:
  preload: true
  allowed_classes: ["yes", "no", "up", "down", "left", "right", "on", "off", "stop", "go"]
  train:
    _target_: datasets.SpeechCommandsDataset
    root_dir: "speech_commands_dataset"
    subset: "training"
    augment: true
  val:
    _target_: datasets.SpeechCommandsDataset
    root_dir: "speech_commands_dataset"
    subset: "validation"
    augment: false
  test:
    _target_: datasets.SpeechCommandsDataset
    root_dir: "speech_commands_dataset"
    subset: "testing"
    augment: false